const START_TEXT = "Do you want to get started with the movie database?"
const ENTER_NAME = "Please, enter your name"
const MESSAGE_EMPTY_FIELD = "You can not save an empty field."
const HALLO = "Hallo "
const AVAILABLE_COMANDS = "Available commands:"
                            + "\n * 'movie add',"
                            + "\n * 'movie view',"
                            + "\n *  'movie numbers',"
                            + "\n *  'filter year',"
                            + "\n *  'filter name',"
                            + "\n *  'end'."
                            + "\n * for a more detailed description, enter the command 'help'." 
const HELP_TEXT = "1. To add a new movie, enter the command 'movie add'."
                    + "\n2. To view movies from the database, enter the command 'movie view'."
                    + "\n3. To search for movies by year of release, enter the command 'filter year'."
                    + "\n4. To search for movies by name, enter the command 'filter name'."
                    + "\n5. To check the number of available movies, enter 'movie numbers'."
                    + "\n6. Shutdown 'end'."
const NO_FOUND_TEXT = " not found text."
const MOVIE_ADD_NAME = "Please, enter name of the movie"
const MOVIE_ADD_YEAR = "Enter a year to search for"
const MOVIE_VALID_YEAR = "The field must be 4-digit."
                            + "\nThe minimum year '1881'"
                             + "\nYou can not specify the future"